---
name: powershell-check

run-name: PowerShell Check

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**/*.ps1"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip_duplicate_actions:
    name: Skip Duplicate Actions
    runs-on: windows-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  powershell_check:
    name: PowerShell Check
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          excludeRule: '"ModuleNotFoundDuringParse"'
          output: results.sarif
          path: .\
          recurse: true
          severity: '"Error", "Warning"'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "results.sarif"
